CREATE DATABASE IF NOT EXISTS  garage_db;

USE garage_db;

CREATE TABLE IF NOT EXISTS  users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lastname VARCHAR(255) NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
  user_id INT PRIMARY KEY,
  role VARCHAR(50) NOT NULL DEFAULT 'client',
  FOREIGN KEY (user_id) REFERENCES users(id)
);
